### ISSUE TITLE
Example .travis.yml

### ISSUE THREAD

**Issue by Requaos** [therecipe/qt#507]
I have been struggling with deciding how best to construct a .travis.yml file for a project built with this binding.

Knowing the details of how qtdeploy calls docker to perform the deployments would be valuable in setting a travis build job using the docker service

**Comment by therecipe** [comment]
Hey

You can probably use something like this:

```yaml
sudo: required
language: go
go:
- 1.9.4
services:
- docker

install:
- docker pull therecipe/qt:linux
- go get -u -v github.com/therecipe/qt/cmd/...

script:
- $GOPATH/bin/qtdeploy -docker build linux
```

Or get some inspiration here: https://github.com/search?l=YAML&q=therecipe%2Fqt&type=Code&utf8=✓
