### ISSUE TITLE
help with integrating into Drone CI pipeline

### ISSUE THREAD

**Issue by dballard** [therecipe/qt#788]
I am attempting to build a therecipe/qt based project in a [Drone CI](https://cloud.drone.io/) pipeline.

My .drone.yml file (docker compose based) is:

```
workspace:
  base: /media/sf_GOPATH1/src
  path: cwtch.im/ui

pipeline:
  build-linux:
    mem_limit: 3G
    image: therecipe/qt:linux
    environment:
      - QT_DIR=/opt/Qt
      - QT_DOCKER='true'
      - QT_API=5.12.0
    commands:
      - echo $QT_DIR
      - export GOPATH=$GOPATH:/media/sf_GOPATH1/
      - echo $GOPATH
      - export PATH=$PATH:/home/user/work/bin:/media/sf_GOPATH1/bin
      - echo $PATH
      - apt-get -qq update && apt-get --no-install-recommends -qq -y install ca-certificates curl git
      - go get
      - qtdeploy build linux
```

So I am attempting to have drone use the therecipe/qt:linux image to do the work. It's first step is to clone the specified project into a directory, the `base+path` directory. and then mount that workspace in different images in the pipeline for different steps and execute different instructions on it

so I define a step using the therecipe/qt:linux image and the execution of what I would hope would be the commands to build it. Unfortunately I am getting the following fail instead:

```
+ echo $QT_DIR
/opt/Qt
+ export GOPATH=$GOPATH:/media/sf_GOPATH1/
+ echo $GOPATH
/home/user/work:/media/sf_GOPATH1/
+ export PATH=$PATH:/home/user/work/bin:/media/sf_GOPATH1/bin
+ echo $PATH
/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/work/bin:/media/sf_GOPATH1/bin
+ apt-get -qq update && apt-get --no-install-recommends -qq -y install ca-certificates curl git
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libnettle6:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
...
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 13367 files and directories currently installed.)
Preparing to unpack .../libnettle6_3.2-1ubuntu0.16.04.1_amd64.deb ...
...
Setting up git-man (1:2.7.4-0ubuntu1.6) ...
Setting up git (1:2.7.4-0ubuntu1.6) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for ca-certificates (20170717~16.04.2) ...
Updating certificates in /etc/ssl/certs...
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
+ go get
# cwtch.im/ui/go/gothings
go/gothings/gcd.go:68:7: this.InvokePopup undefined (type *GrandCentralDispatcher has no field or method InvokePopup)
go/gothings/gcd.go:72:9: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:73:7: this.InvokePopup undefined (type *GrandCentralDispatcher has no field or method InvokePopup)
go/gothings/gcd.go:77:13: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:78:29: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:79:37: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:84:37: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:90:52: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:92:8: this.InvokePopup undefined (type *GrandCentralDispatcher has no field or method InvokePopup)
go/gothings/gcd.go:98:35: this.CurrentOpenConversation undefined (type *GrandCentralDispatcher has no field or method CurrentOpenConversation)
go/gothings/gcd.go:98:35: too many errors 
```

on my computer, just running `qtdeploy build linux` in the root directory of our project in $GOPATH/src/cwtch.im/ui works fine. I feel like I'm doing something wrong with the image. If anything jumps out at you that would be greatly appreciated
thanks!
